name: HR server (Push)

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the gold branch
  push:
    branches: [gold]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache-node-modules-pre
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-hr-server-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install node_modules
        if: steps.cache-node-modules-pre.outputs.cache-hit != 'true'
        run: yarn install

  check:
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-hr-server-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Check linting
        run: yarn lint

      - name: Check prettier
        run: yarn format:check

  build:
    needs: [check]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-hr-server-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Build HR project
        run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-hr-server-ts
          path: dist

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist-hr-server-ts
          path: dist
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
